const styles={
    shopNowParentContainer:{
        width:'250px',
        height:'150px',
        fontFamily: 'Titillium Web sans-serif',
    },
    shopNowCost:{
        display:'flex',
        justifyContent:'right',
        width:'86%',

       
    },
    shopNowIcons:{
        display:'flex',
        justifyContent:'space-evenly',
        color:'#b9b9b9',
       cursor:'pointer',
       marginTop:'10px',
       '&:hover':{
           color:'black'
       }
    },
    shopNowIcons1:{
        display:'flex',
        justifyContent:'space-between',
        color:'#b9b9b9',
       cursor:'pointer',
       '&:hover':{
           color:'black'
       }
    },
    shopNowIcons2:{
        display:'flex',
        justifyContent:'space-between',
        color:'#b9b9b9',
       cursor:'pointer',
       '&:hover':{
           color:'black'
       }
    },
    shopNowIcons3:{
        display:'flex',
        justifyContent:'space-between',
        color:'#b9b9b9',
       cursor:'pointer',
       '&:hover':{
           color:'black'
       }
    },
    shopNowIcons4:{
        display:'flex',
        justifyContent:'space-between',
        color:'#b9b9b9',
       cursor:'pointer',
       '&:hover':{
           color:'black'
       }
    },

    showNowBtn:{
        marginTop:'15px',        
    },
    btnClr:{
        backgroundColor:'#152e59',
        width:'180px',
        height:'50px',
        TextDecoration:'none',
        '&:hover':{
            backgroundColor:'#152e59',

        }
    }
}
export{
    styles
}