export const UPDATE_VARIANTS = "UPDATE_VARIANTS";
export const UPDATE_CONFIGURATOR = "UPDATE_CONFIGURATOR";

export const SET_SELECTED_VARIANT = "SET_SELECTED_VARIANT";
export const SHOW_MEASUREMENT = "SHOW_MEASUREMENT";

export const SET_USER_INFORMATION = "SET_USER_INFORMATION";
export const PARENT_VARIANTS_GET = "PARENT_VARIANTS_GET"
export const MEASUREMENT_VARIANT_DATA = "MEASUREMENT_VARIANT_DATA"
export const DASHBOARD_CUSTOMERS_GET = "DASHBOARD_CUSTOMERS_GET"
export const SELECTED_CUSTOMER_ID = "SELECTED_CUSTOMER_ID"
export const GET_SELECTED_CUSTOMER = "GET_SELECTED_CUSTOMER"
export const PURCHASE_ITEM = "PURCHASE_ITEM"

export const ADD_TO_CART = "ADD_TO_CART"

export const SELECT_MEASUREMENTS = "SELECT_MEASUREMENTS"