export const UPDATE_VARIANTS = "UPDATE_VARIANTS";
export const UPDATE_CONFIGURATOR = "UPDATE_CONFIGURATOR";

export const SET_SELECTED_VARIANT = "SET_SELECTED_VARIANT";
export const SHOW_MEASUREMENT = "SHOW_MEASUREMENT";
