const styles={
    measurementSelectionContainer :{
         backgroundColor:'#e7e7e7',
         display:'flex',
         justifyContent:'space-evenly',
         flexWrap:'wrap',
        marginTop:'10px',
    },
    measurementChoices:{
        textAlign:'left',
        display:'flex',
        flexWrap:'wrap',
        width:'200px',
    },
    measurementImg:{
        width:'400px',
    },
    measurementdescription:{
        width:'200px',
        marginTop:'10px',
        textAlign:'left',
        paddingLeft:'10px',
        paddingRight:'10px'
    },
    inputField:{
        width:'30px'
    }
}
export{
    styles
}